# Generated by Django 5.2.7 on 2025-11-07 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mobil',
            new_name='mobile',
        ),
    ]
